# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_app', '0003_auto_20151219_0403'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Question')),
                ('slug', models.CharField(max_length=255)),
                ('views', models.IntegerField(db_column='view_count_cache', default=0, editable=False)),
                ('has_answer', models.BooleanField(default=False)),
                ('rating_votes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating_score', models.IntegerField(blank=True, default=0, editable=False)),
                ('accepted_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='comments_app.TappedComment')),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_app.TappedComment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
